# Generated by Django 5.2.17 on 2026-09-27 08:54

import accounts.uploads
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_unit_directory', 'Unit directory'), ('manage_unit_users', 'User management'), ('view_projects', 'Projects'), ('work_on_tasks', 'My tasks'), ('review_code', 'Code reviews'), ('assign_tasks', 'Task assignment'), ('manage_dev_team', 'Team overview'), ('view_courses', 'Courses'), ('view_own_progress', 'My progress'), ('teach_classes', 'My classes'), ('grade_students', 'Grading'), ('manage_enquiries', 'Enquiries'), ('manage_enrollments', 'Enrollments'), ('manage_batches', 'Batches'), ('view_training_reports', 'Training reports'), ('write_content', 'My assignments'), ('conduct_research', 'Research'), ('review_content', 'Quality review'), ('manage_production', 'Production pipeline'), ('manage_leads', 'Leads & orders'), ('view_sales_reports', 'Sales reports'), ('manage_sales_team', 'Sales team'), ('manage_employee_records', 'Employee records'), ('manage_payroll', 'Staff payroll'), ('view_all_employee_records', 'Company-wide employee records')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Yeticode Innovations', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Staff portal', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='PNG, JPG or WebP, up to 2 MB. A square image works best.', upload_to=accounts.uploads.logo_upload_to, validators=[accounts.uploads.validate_image])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'company settings',
                'verbose_name_plural': 'company settings',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.PositiveSmallIntegerField(default=1, help_text='Seniority within the unit; 1 is the most junior.')),
                ('permissions', models.ManyToManyField(blank=True, help_text='What people with this role are allowed to do.', related_name='roles', to='auth.permission')),
                ('unit', models.ForeignKey(blank=True, help_text='Leave empty only for a company-wide role such as Head HR.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='accounts.unit')),
            ],
            options={
                'ordering': ['unit__name', 'rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secondary_email', models.EmailField(blank=True, help_text='An optional second address. People sign in with their primary email.', max_length=254)),
                ('avatar', models.ImageField(blank=True, help_text='Profile photo: PNG, JPG or WebP, up to 2 MB.', upload_to=accounts.uploads.avatar_upload_to, validators=[accounts.uploads.validate_image])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, help_text='Required for everyone except Super Admins. The role decides the unit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role')),
            ],
            options={
                'ordering': ['username'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_superuser', True), ('role__isnull', True)), models.Q(('is_superuser', False), ('role__isnull', False)), _connector='OR'), name='user_is_super_admin_xor_has_role')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('unit', 'code'), name='unique_role_code_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_role_name_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('code',), name='unique_company_wide_role_code'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('name',), name='unique_company_wide_role_name'),
        ),
    ]
