# Generated by Django 5.1.15 on 2026-09-27 03:55

import django.db.models.deletion
from django.db import migrations, models


def give_students_unit_directory(apps, schema_editor):
    """Databases seeded before this change: Students now see their unit directory.

    New databases get this from the seed catalog instead.
    """
    Role = apps.get_model("accounts", "Role")
    Permission = apps.get_model("auth", "Permission")
    student = Role.objects.filter(unit__code="training", code="student").first()
    perm = Permission.objects.filter(
        content_type__app_label="accounts", codename="view_unit_directory"
    ).first()
    if student and perm:
        student.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capability",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("view_unit_directory", "Unit directory"),
                    ("view_projects", "Projects"),
                    ("work_on_tasks", "My tasks"),
                    ("review_code", "Code reviews"),
                    ("assign_tasks", "Task assignment"),
                    ("manage_dev_team", "Team overview"),
                    ("view_courses", "Courses"),
                    ("view_own_progress", "My progress"),
                    ("teach_classes", "My classes"),
                    ("grade_students", "Grading"),
                    ("manage_enquiries", "Enquiries"),
                    ("manage_enrollments", "Enrollments"),
                    ("manage_batches", "Batches"),
                    ("view_training_reports", "Training reports"),
                    ("write_content", "My assignments"),
                    ("conduct_research", "Research"),
                    ("review_content", "Quality review"),
                    ("manage_production", "Production pipeline"),
                    ("manage_leads", "Leads & orders"),
                    ("view_sales_reports", "Sales reports"),
                    ("manage_sales_team", "Sales team"),
                    ("manage_employee_records", "Employee records"),
                    ("view_all_employee_records", "Company-wide employee records"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="role",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty only for a company-wide role such as Head HR.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roles",
                to="accounts.unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unit__isnull", True)),
                fields=("code",),
                name="unique_company_wide_role_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unit__isnull", True)),
                fields=("name",),
                name="unique_company_wide_role_name",
            ),
        ),
        migrations.RunPython(give_students_unit_directory, migrations.RunPython.noop),
    ]
