# Generated by Django 5.2.17 on 2026-09-27 10:58

from django.conf import settings
from django.db import migrations, models

from accounts.usernames import slugify_username, unique_username


def set_domain_and_short_usernames(apps, schema_editor):
    """Existing databases: give the company a domain and turn "name@domain" usernames into "name"."""
    CompanySettings = apps.get_model("accounts", "CompanySettings")
    User = apps.get_model("accounts", "User")
    for company in CompanySettings.objects.all():
        if not company.domain:
            company.domain = settings.DEFAULT_EMAIL_DOMAIN.lower()
            company.save(update_fields=["domain"])

    taken = set()
    for user in User.objects.order_by("date_joined", "pk"):
        base = slugify_username(user.username) or slugify_username(user.email) or slugify_username(user.first_name)
        user.username = unique_username(base, taken)
        taken.add(user.username)
        user.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='domain',
            field=models.CharField(blank=True, help_text='e.g. corecontent.com. Usernames are completed with it: abhishekojha@corecontent.com.', max_length=120),
        ),
        migrations.RunPython(set_domain_and_short_usernames, migrations.RunPython.noop),
    ]
