# Generated by Django 5.2.17 on 2026-09-27 05:18

from django.db import migrations


UNIT_ADMIN_ROLES = [
    ("web", "team_lead"),
    ("training", "training_manager"),
    ("content", "production_manager"),
]


def give_senior_roles_user_management(apps, schema_editor):
    """Databases seeded before this change: each unit's senior role manages its users.

    New databases get this from the seed catalog instead.
    """
    Role = apps.get_model("accounts", "Role")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    roles = [
        role for unit, code in UNIT_ADMIN_ROLES
        if (role := Role.objects.filter(unit__code=unit, code=code).first())
    ]
    if not roles:
        return
    content_type, _ = ContentType.objects.get_or_create(app_label="accounts", model="capability")
    perm, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename="manage_unit_users",
        defaults={"name": "User management"},
    )
    for role in roles:
        role.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_wide_roles"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capability",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("view_unit_directory", "Unit directory"),
                    ("manage_unit_users", "User management"),
                    ("view_projects", "Projects"),
                    ("work_on_tasks", "My tasks"),
                    ("review_code", "Code reviews"),
                    ("assign_tasks", "Task assignment"),
                    ("manage_dev_team", "Team overview"),
                    ("view_courses", "Courses"),
                    ("view_own_progress", "My progress"),
                    ("teach_classes", "My classes"),
                    ("grade_students", "Grading"),
                    ("manage_enquiries", "Enquiries"),
                    ("manage_enrollments", "Enrollments"),
                    ("manage_batches", "Batches"),
                    ("view_training_reports", "Training reports"),
                    ("write_content", "My assignments"),
                    ("conduct_research", "Research"),
                    ("review_content", "Quality review"),
                    ("manage_production", "Production pipeline"),
                    ("manage_leads", "Leads & orders"),
                    ("view_sales_reports", "Sales reports"),
                    ("manage_sales_team", "Sales team"),
                    ("manage_employee_records", "Employee records"),
                    ("view_all_employee_records", "Company-wide employee records"),
                ],
            },
        ),
        migrations.RunPython(give_senior_roles_user_management, migrations.RunPython.noop),
    ]
