# Generated by Django 5.2.17 on 2026-09-27 05:53

import accounts.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Yeticode Innovations', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Staff portal', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='PNG, JPG or WebP, up to 2 MB. A square image works best.', upload_to=accounts.uploads.logo_upload_to, validators=[accounts.uploads.validate_image])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'company settings',
                'verbose_name_plural': 'company settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo: PNG, JPG or WebP, up to 2 MB.', upload_to=accounts.uploads.avatar_upload_to, validators=[accounts.uploads.validate_image]),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(blank=True, help_text='An optional second address. People sign in with their primary email.', max_length=254),
        ),
    ]
