# Generated by Django 5.2.17 on 2026-09-27 06:19

from django.db import migrations

PAYROLL_ROLES = [("content", "production_manager"), ("content", "hr")]


def give_payroll_to_production_manager_and_hr(apps, schema_editor):
    """Databases seeded before this change: the content unit's Production Manager and HR run payroll.

    New databases get this from the seed catalog instead.
    """
    Role = apps.get_model("accounts", "Role")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    roles = [
        role for unit, code in PAYROLL_ROLES
        if (role := Role.objects.filter(unit__code=unit, code=code).first())
    ]
    if not roles:
        return
    content_type, _ = ContentType.objects.get_or_create(app_label="accounts", model="capability")
    perm, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename="manage_payroll",
        defaults={"name": "Staff payroll"},
    )
    for role in roles:
        role.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profiles_and_branding"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capability',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_unit_directory', 'Unit directory'), ('manage_unit_users', 'User management'), ('view_projects', 'Projects'), ('work_on_tasks', 'My tasks'), ('review_code', 'Code reviews'), ('assign_tasks', 'Task assignment'), ('manage_dev_team', 'Team overview'), ('view_courses', 'Courses'), ('view_own_progress', 'My progress'), ('teach_classes', 'My classes'), ('grade_students', 'Grading'), ('manage_enquiries', 'Enquiries'), ('manage_enrollments', 'Enrollments'), ('manage_batches', 'Batches'), ('view_training_reports', 'Training reports'), ('write_content', 'My assignments'), ('conduct_research', 'Research'), ('review_content', 'Quality review'), ('manage_production', 'Production pipeline'), ('manage_leads', 'Leads & orders'), ('view_sales_reports', 'Sales reports'), ('manage_sales_team', 'Sales team'), ('manage_employee_records', 'Employee records'), ('manage_payroll', 'Staff payroll'), ('view_all_employee_records', 'Company-wide employee records')]},
        ),
        migrations.RunPython(give_payroll_to_production_manager_and_hr, migrations.RunPython.noop),
    ]
