# Generated by Django 5.2.17 on 2026-09-27 06:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_payroll_capability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPay',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pay', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('words_per_rate', models.PositiveIntegerField(default=6000, help_text='Words that earn one rate amount, e.g. 6000.')),
                ('words_rate_amount', models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='NPR paid per that many words.', max_digits=10)),
                ('hours_per_rate', models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='Hours that earn one rate amount, e.g. 8.', max_digits=6)),
                ('hours_rate_amount', models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='NPR paid per that many hours.', max_digits=10)),
                ('daily_extra', models.BooleanField(default=False, help_text='This person earns extras day by day, so each extra is dated.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'staff pay',
                'verbose_name_plural': 'staff pay',
            },
        ),
        migrations.CreateModel(
            name='PayExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The first day of the month this is paid in.')),
                ('date', models.DateField(blank=True, help_text='The day the work was done, for daily extras.', null=True)),
                ('kind', models.CharField(choices=[('words', 'Extra task (words)'), ('hours', 'Extra task (hours)'), ('performance', 'Performance'), ('effort', 'Effort')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Words written or hours worked.', max_digits=12, null=True)),
                ('per_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_extras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month', 'date', 'created_at'],
                'indexes': [models.Index(fields=['month', 'staff'], name='payroll_pay_month_d1bcb8_idx')],
            },
        ),
    ]
