# Generated by Django 5.2.17 on 2026-09-27 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payextra',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', False), ('kind__in', ['words', 'hours'])), fields=('staff', 'date', 'kind'), name='one_measured_extra_per_day'),
        ),
    ]
