import {
  AuditOutlined,
  WalletOutlined,
  BarChartOutlined,
  BookOutlined,
  CalendarOutlined,
  CheckSquareOutlined,
  ClusterOutlined,
  CodeOutlined,
  CustomerServiceOutlined,
  DeploymentUnitOutlined,
  EditOutlined,
  ExperimentOutlined,
  FileSearchOutlined,
  FundOutlined,
  GlobalOutlined,
  IdcardOutlined,
  LineChartOutlined,
  ProjectOutlined,
  ReadOutlined,
  RiseOutlined,
  SafetyCertificateOutlined,
  ScheduleOutlined,
  SolutionOutlined,
  TeamOutlined,
  TrophyOutlined,
  UserAddOutlined,
  UsergroupAddOutlined,
} from '@ant-design/icons'

// Icon and accent for each dashboard section. Unknown keys fall back to a neutral card.
export const CAPABILITY_META = {
  view_unit_directory: { icon: TeamOutlined, color: '#3451d1' },
  manage_unit_users: { icon: UserAddOutlined, color: '#3451d1' },
  manage_users: { icon: UsergroupAddOutlined, color: '#3451d1' },
  manage_roles: { icon: SafetyCertificateOutlined, color: '#8b3fd9' },
  view_projects: { icon: ProjectOutlined, color: '#3451d1' },
  work_on_tasks: { icon: CheckSquareOutlined, color: '#0b7285' },
  review_code: { icon: CodeOutlined, color: '#5f3dc4' },
  assign_tasks: { icon: DeploymentUnitOutlined, color: '#d9480f' },
  manage_dev_team: { icon: ClusterOutlined, color: '#2b8a3e' },
  view_courses: { icon: BookOutlined, color: '#0f9d76' },
  view_own_progress: { icon: TrophyOutlined, color: '#c47f00' },
  teach_classes: { icon: ReadOutlined, color: '#0f9d76' },
  grade_students: { icon: AuditOutlined, color: '#5f3dc4' },
  manage_enquiries: { icon: CustomerServiceOutlined, color: '#0b7285' },
  manage_enrollments: { icon: SolutionOutlined, color: '#3451d1' },
  manage_batches: { icon: CalendarOutlined, color: '#d9480f' },
  view_training_reports: { icon: BarChartOutlined, color: '#2b8a3e' },
  write_content: { icon: EditOutlined, color: '#8b3fd9' },
  conduct_research: { icon: ExperimentOutlined, color: '#0b7285' },
  review_content: { icon: FileSearchOutlined, color: '#5f3dc4' },
  manage_production: { icon: ScheduleOutlined, color: '#d9480f' },
  manage_leads: { icon: RiseOutlined, color: '#2b8a3e' },
  view_sales_reports: { icon: LineChartOutlined, color: '#3451d1' },
  manage_sales_team: { icon: FundOutlined, color: '#c2255c' },
  manage_employee_records: { icon: IdcardOutlined, color: '#c47f00' },
  view_all_employee_records: { icon: GlobalOutlined, color: '#c47f00' },
  manage_payroll: { icon: WalletOutlined, color: '#2b8a3e' },
}

export function capabilityMeta(key) {
  return CAPABILITY_META[key] ?? { icon: ProjectOutlined, color: '#64748b' }
}
