# Generated by Django 5.2.17 on 2026-09-27 08:54

import django.core.validators
import django.db.models.deletion
import team.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Chat message ids are UUIDs; this sequence gives each message an increasing `seq` for ordering.
        migrations.RunSQL(
            "CREATE SEQUENCE IF NOT EXISTS team_chatmessage_seq",
            reverse_sql="DROP SEQUENCE IF EXISTS team_chatmessage_seq",
        ),
        migrations.CreateModel(
            name='ChatPresence',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat_presence', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_seen', models.DateTimeField()),
                ('delivered_up_to', models.PositiveBigIntegerField(default=0, help_text='The seq of the newest message fetched.')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='office_hours', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('work_days', models.CharField(default='6,0,1,2,3,4', help_text='Comma-separated weekday numbers, Monday = 0. Reminders only come on these days.', max_length=20)),
                ('reminders', models.BooleanField(default=True, help_text='Remind 30, 15 and 5 minutes before the shift and 5 minutes before it ends.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'office hours',
            },
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='chat_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(db_default=team.models.NextMessageSeq(), editable=False, unique=True)),
                ('body', models.TextField(blank=True, max_length=4000)),
                ('audio', models.FileField(blank=True, storage=team.models.private_storage, upload_to=team.models.voice_upload_to)),
                ('audio_duration', models.PositiveIntegerField(blank=True, help_text='Seconds.', null=True)),
                ('attachment', models.FileField(blank=True, max_length=200, storage=team.models.private_storage, upload_to=team.models.attachment_upload_to)),
                ('attachment_name', models.CharField(blank=True, help_text="The file's original name.", max_length=255)),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='team.chatgroup')),
                ('recipient', models.ForeignKey(blank=True, help_text='Empty for the team room.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['sender', 'recipient', 'seq'], name='team_chatme_sender__733b12_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_seq', models.PositiveBigIntegerField(default=0, help_text='The seq of the last message seen.')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.chatgroup')),
                ('peer', models.ForeignKey(blank=True, help_text='The colleague, for a one-to-one chat.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'peer'), name='one_read_marker_per_conversation'), models.UniqueConstraint(condition=models.Q(('group__isnull', True), ('peer__isnull', True)), fields=('user',), name='one_team_read_marker'), models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('user', 'group'), name='one_group_read_marker')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='The first day of the month the review is for.')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('author', 'subject', 'month'), name='one_review_per_person_per_month'), models.CheckConstraint(condition=models.Q(('author', models.F('subject')), _negated=True), name='no_self_review')],
            },
        ),
    ]
