# Generated by Django 5.2.17 on 2026-09-27 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_payroll_capability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='office_hours', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('work_days', models.CharField(default='6,0,1,2,3,4', help_text='Comma-separated weekday numbers, Monday = 0. Reminders only come on these days.', max_length=20)),
                ('reminders', models.BooleanField(default=True, help_text='Remind 30, 15 and 5 minutes before the shift and 5 minutes before it ends.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'office hours',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Empty for the team room.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['sender', 'recipient', 'id'], name='team_chatme_sender__18caf0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_id', models.PositiveBigIntegerField(default=0)),
                ('peer', models.ForeignKey(blank=True, help_text='Empty for the team room.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'peer'), name='one_read_marker_per_conversation'), models.UniqueConstraint(condition=models.Q(('peer__isnull', True)), fields=('user',), name='one_team_read_marker')],
            },
        ),
    ]
