# Generated by Django 5.2.17 on 2026-09-27 07:50

import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio',
            field=models.FileField(blank=True, storage=team.models.private_storage, upload_to=team.models.voice_upload_to),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds.', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
