# Generated by Django 5.2.17 on 2026-09-27 08:01

import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_voice_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, max_length=200, storage=team.models.private_storage, upload_to=team.models.attachment_upload_to),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, help_text="The file's original name.", max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
