# Generated by Django 5.2.17 on 2026-09-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_payroll_capability'),
        ('team', '0004_chat_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatPresence',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat_presence', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_seen', models.DateTimeField()),
                ('delivered_up_to', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='chatread',
            name='one_team_read_marker',
        ),
        migrations.AlterField(
            model_name='chatread',
            name='peer',
            field=models.ForeignKey(blank=True, help_text='The colleague, for a one-to-one chat.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='chat_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='team.chatgroup'),
        ),
        migrations.AddField(
            model_name='chatread',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.chatgroup'),
        ),
        migrations.AddConstraint(
            model_name='chatread',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', True), ('peer__isnull', True)), fields=('user',), name='one_team_read_marker'),
        ),
        migrations.AddConstraint(
            model_name='chatread',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('user', 'group'), name='one_group_read_marker'),
        ),
    ]
